on: push

permissions:
  contents: write

jobs:
  build_stl:
    runs-on: ubuntu-latest
    name: Build STL files
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          ref: latest
          description: Latest version
      - name: Run make
        uses: ./
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: stl.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
